config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'simple_pages/about'
  get 'simple_pages/posts'
  get 'simple_pages/hireme'
  get 'simple_pages/index'
  root 'simple_pages#landing_page'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @test_variable = 42
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :description, :image_url, :theme)
    end
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def landing_page
    @featured_post = Post.first
    @posts = Post.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Design in China</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'simple_pages/header' %>

    <%= yield %>

    <%= render 'simple_pages/footer' %>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

  <div class="field">
  <%= form.label :theme %><br>
  <%= form.text_field :theme %>
</div>
<% end %>

app/views/posts/edit.html.erb
<h5>Editing Post</h5>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid posts-content">
  <div class="row">
    <div class="col-lg-10 col-sm-12 main-bar">
      <div class="container-fluid">
        <div class="post-category">
          <h5>New posts</h5>
        </div><!-- /post-category -->
        <div class="row">
          <% @posts.each do |post| %>
          <div class="col-lg-4 col-md-4 col-sm-12 theme-image">
            <%= image_tag(post.image_url, class: "img img-fluid") %>
          </div><!-- /theme-image -->
          <div class="col-lg-8 col-md-8 col-sm-12 post-content">
            <div class="theme-category">
              <h6><a href="#"><%= post.theme %></h6></a>
            </div><!-- /theme-category -->
            <div class="theme-title">
              <h2><a href="#"><%= post.name %></h2></a>
            </div><!-- /theme-title -->
            <div class="post-text">
              <p><%= post.description %></p>
            </div><!-- /post-text -->
            <div class="post-manage">
              <%= link_to 'Show', post %> / <%= link_to 'Edit', edit_post_path(post) %> / <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div><!-- /post-manage -->
          </div><!-- /col-lg-8 col-sm-12 -->
          <% end %>
        </div><!-- /row -->
      </div><!-- /container-fluid -->
    </div><!-- /main-bar -->
    <div class="col-lg-2 col-sm-12">
      <div class="side-bar">
        <div class="sidebar-topic">
          <h5>About</h5>
          <p>Design in China is a blog about Design, photography and food in China. Having lived in Beijing for over 10 years I call this place my home. Beeing a designer and a photographer I would like to share all things new and traditional in this area. Plus I am a great Chinese food-lover, and want to sahre some of my favourite recipes and new encounterings with you!</p>
          <%= image_tag 'about.270x270.jpg', class: "img img-fluid" %>
        </div><!-- /sidebar-topic -->
        <div class="sidebar-topic">
          <h5>Social Links</h5>
          <div class="sidebar-social">
            <div class="sidebar-icon">
              <%= image_tag('instagram.svg', class: "img-fluid") %>
            </div><!-- /sidebar-social -->
            <div class="sidebar-icon">
              <%= image_tag('linkedin.svg', class: "img-fluid") %>
            </div><!-- /sidebar-social -->
            <div class="sidebar-icon">
              <%= image_tag('pinterest.svg', class: "img-fluid") %>
            </div><!-- /sidebar-social -->
          </div>
        </div><!-- /sidebar-topic -->
    </div><!-- /col-lg-2 col-sm-12 -->
  </div><!-- /row -->
</div><!-- /posts-content -->
<div class="post-new">
  <%= link_to 'New Post', new_post_path %>
</div><!-- /post-new -->

app/views/posts/new.html.erb
<h5>New Post</h5>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @post.image_url %>
</p>

<p>
  <strong>Theme:</strong>
  <%= @post.theme %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/simple_pages/_articles.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid posts-content">
  <div class="row">
    <div class="col-lg-10 col-sm-12 main-bar">
      <div class="container-fluid">
        <div class="post-category">
          <h5>New posts</h5>
        </div><!-- /post-category -->
        <div class="row">
          <% @posts.each do |post| %>
          <div class="col-lg-4 col-md-4 col-sm-12 theme-image">
            <%= image_tag(post.image_url, class: "img img-fluid") %>
          </div><!-- /theme-image -->
          <div class="col-lg-8 col-md-8 col-sm-12 post-content">
            <div class="theme-category">
              <h6><a href="#"><%= post.theme %></h6></a>
            </div><!-- /theme-category -->
            <div class="theme-title">
              <h2><a href="#"><%= post.name %></h2></a>
            </div><!-- /theme-title -->
            <div class="post-text">
              <p><%= post.description %></p>
            </div><!-- /post-text -->
            <div class="post-manage">
              <%= link_to 'Show', post %> / <%= link_to 'Edit', edit_post_path(post) %> / <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div><!-- /post-manage -->
          </div><!-- /col-lg-8 col-sm-12 -->
          <% end %>
        </div><!-- /row -->
      </div><!-- /container-fluid -->
    </div><!-- /main-bar -->
    <div class="col-lg-2 col-sm-12">
      <div class="side-bar">
        <div class="sidebar-topic">
          <h5>About</h5>
          <p>Design in China is a blog about Design, photography and food in China. Having lived in Beijing for over 10 years I call this place my home. Beeing a designer and a photographer I would like to share all things new and traditional in this area. Plus I am a great Chinese food-lover, and want to sahre some of my favourite recipes and new encounterings with you!</p>
          <%= image_tag 'about.270x270.jpg', class: "img img-fluid" %>
        </div><!-- /sidebar-topic -->
        <div class="sidebar-topic">
          <h5>Social Links</h5>
          <div class="sidebar-social">
            <div class="sidebar-icon">
              <%= image_tag('instagram.svg', class: "img-fluid") %>
            </div><!-- /sidebar-social -->
            <div class="sidebar-icon">
              <%= image_tag('linkedin.svg', class: "img-fluid") %>
            </div><!-- /sidebar-social -->
            <div class="sidebar-icon">
              <%= image_tag('pinterest.svg', class: "img-fluid") %>
            </div><!-- /sidebar-social -->
          </div>
        </div><!-- /sidebar-topic -->
    </div><!-- /col-lg-2 col-sm-12 -->
  </div><!-- /row -->
</div><!-- /posts-content -->
<div class="post-new">
  <%= link_to 'New Post', new_post_path %>
</div><!-- /post-new -->

app/views/simple_pages/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide landing-carousel" data-ride="carousel">

  <!-- indicators -->
  <ol class="carousel-indicators">
    <% @posts.each_with_index do |post| %>
    <li data-target="#carouselExampleIndicators" data-slide-to="0"></li>
    <% end %>
  </ol>

  <!-- wrapper for slides -->
  <div class="carousel-inner">
    <% @posts.each do |post| %>
    <div class="carousel-item<%= " active" if post == @posts.first %>">
      <%= image_tag(post.image_url, class: "img-fluid jumbotron-images") %>
      <div class="carousel-caption d-none d-md-block">
        <div class="theme-category mainpage-category">
          <h6><a href="#"><%= post.theme %></h6></a>
        </div>
        <div class="theme-title mainpage-title">
          <h5><a href="#"><%= post.name %></h5></a>
        </div>
        <div class="post-text mainpage-text">
          <p><%= post.description %></p>
        </div>
      </div>
    </div>
    <% end %>
  </div>


<!-- controls -->
<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
  <span class="sr-only">Previous</span>
</a>
<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
  <span class="carousel-control-next-icon" aria-hidden="true"></span>
  <span class="sr-only">Next</span>
</a>
  </div>
</div>

app/views/simple_pages/_design.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid posts-content">
  <div class="row">
    <div class="col-lg-10 col-sm-12 main-bar">
      <div class="container-fluid">
        <div class="post-category">
          <h5>New posts</h5>
        </div><!-- /post-category -->
        <div class="row">
          <% @posts.each do |post| %>
          <div class="col-lg-4 col-md-4 col-sm-12 theme-image">
            <%= image_tag(post.image_url, class: "img img-fluid") %>
          </div><!-- /theme-image -->
          <div class="col-lg-8 col-md-8 col-sm-12 post-content">
            <div class="theme-category">
              <h6><a href="#"><%= post.theme %></h6></a>
            </div><!-- /theme-category -->
            <div class="theme-title">
              <h2><a href="#"><%= post.name %></h2></a>
            </div><!-- /theme-title -->
            <div class="post-text">
              <p><%= post.description %></p>
            </div><!-- /post-text -->
            <div class="post-manage">
              <%= link_to 'Show', post %> / <%= link_to 'Edit', edit_post_path(post) %> / <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div><!-- /post-manage -->
          </div><!-- /col-lg-8 col-sm-12 -->
          <% end %>
        </div><!-- /row -->
      </div><!-- /container-fluid -->
    </div><!-- /main-bar -->
    <div class="col-lg-2 col-sm-12">
      <div class="side-bar">
        <div class="sidebar-topic">
          <h5>About</h5>
          <p>Design in China is a blog about Design, photography and food in China. Having lived in Beijing for over 10 years I call this place my home. Beeing a designer and a photographer I would like to share all things new and traditional in this area. Plus I am a great Chinese food-lover, and want to sahre some of my favourite recipes and new encounterings with you!</p>
          <%= image_tag 'about.270x270.jpg', class: "img img-fluid" %>
        </div><!-- /sidebar-topic -->
        <div class="sidebar-topic">
          <h5>Social Links</h5>
          <div class="sidebar-social">
            <div class="sidebar-icon">
              <%= image_tag('instagram.svg', class: "img-fluid") %>
            </div><!-- /sidebar-social -->
            <div class="sidebar-icon">
              <%= image_tag('linkedin.svg', class: "img-fluid") %>
            </div><!-- /sidebar-social -->
            <div class="sidebar-icon">
              <%= image_tag('pinterest.svg', class: "img-fluid") %>
            </div><!-- /sidebar-social -->
          </div>
        </div><!-- /sidebar-topic -->
    </div><!-- /col-lg-2 col-sm-12 -->
  </div><!-- /row -->
</div><!-- /posts-content -->
<div class="post-new">
  <%= link_to 'New Post', new_post_path %>
</div><!-- /post-new -->

app/views/simple_pages/_footer.html.erb
<div class="footer-content">
(c) 2018 by Design in China 设计在中国
</div>

app/views/simple_pages/_header.html.erb
<div class="logo"><%= image_tag 'Logo.designinchina.svg', class: "img-fluid", alt: 'logo' %></div>

<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light main-navigation">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li><%= link_to "Design", simple_pages_about_path %></li>
      <li><%= link_to "Photography", simple_pages_about_path %></li>
      <li><%= link_to "Recipes", simple_pages_hireme_path %></li>
      <li><%= link_to "About", simple_pages_about_path %></li>
    </ul>
  </div>
</nav>

app/views/simple_pages/about.html.erb
<h5>About</h5>
<p>Find me in app/views/simple_pages/about.html.erb</p>

app/views/simple_pages/hireme.html.erb
<h5>Hire me!</h5>
<p>Find me in app/views/simple_pages/hireme.html.erb</p>

app/views/simple_pages/index.html.erb
<h5>Design in China! 设计在中国</h5>
<p>This blog is about everything connected with Design that is related to China.</p>
<p>Welcome! The date and time is <%= Time.now %></p>

app/views/simple_pages/index0.html.erb
  <div class="order-content">
    <h1>Orders</h1>
    <div class="row order-table">
      <% @orders.each do |order| %>
      <div class="col-sm">
        <h2><strong>Order # <%= order.id %></strong></h2>
        <h2><%= link_to order.product.name, order %></h2>
        <%= image_tag(order.product.image_url, class: "img-fluid order-img") %>
        <div class="order-description">
          <p><%= order.product.description %></p>
        </div>
        <div class="order-price"
          <strong>$ <%= order.product.price %></strong>
        </div>
      </div><!-- /col -->
      <% end %>
    </div>
</div>

app/views/simple_pages/landing_page.html.erb
<%= render 'simple_pages/carousel' %>
<%= render 'simple_pages/articles' %>
<%= render 'simple_pages/design' %>

app/views/simple_pages/posts.html.erb
<h5>Posts</h5>
<p>Find me in app/views/simple_pages/posts.html.erb</p>